- image:  # Root key for the image definition
    registry: "image-registry.vo.elte.hu"  # image registry url
    command: "/entrypoint.sh"  # Command to run when the container starts
    os: "Ubuntu 24.04"  # Operating system of the Docker image
    app: "RStudio with R and Python"  # Application provided by the Docker image
    hardware: "CPU only"  # Hardware support required by the Docker image
    packages: "Basic R packages for handling data and plotting results, conda ..."  # Packages included in the Docker image
    image_type: "projectimage"  # Type of the image, e.g., project image
    thumbnail: "rstudio"  # Thumbnail image associated with the Docker image
    envs:  # Environment variables for the Docker image
      IDE_SUFFIX: "auth-sign-in"  # Environment variable key-value pair
    proxy:  # Proxy settings for the Docker image
      rstudio:  # Proxy name
           register: True  # Whether to register the piroxy into the configurable-http-proxy
           svc_port: 8000  # Service port for the proxy
      testurl:  # Another proxy name
           svc_port: 9000  # Service port for the proxy
           register: False  # Whether to register the proxy
           basepath: "notebook/{container.label}"  # Base path for the proxy
    serviceview:  # Service view settings for the Docker image
      rstudio:  # Service view name
        proxy: "rstudio"  # Proxy associated with the service view
        suffix: "auth-sign-in"  # URL suffix for the service view
        openable: True  # Whether the service view is openable from the environments page
        pass_token: False  # Whether to pass token to the service view
        icon: "rstudio_logo.png"  # Icon for the service view
      testurl:  # Another service view name
        proxy: "testurl"  # Proxy associated with the service view
        suffix: ""  # URL suffix for the service view
        openable: False  # Whether the service view is openable  from the environments page
        pass_token: False  # Whether to pass token to the service view
        icon: "test_logo.png"  # Icon for the service view
