- image:
    name: "image-registry.vo.elte.hu/denario-app"
    command: "/entrypoint.sh"
    os: "Ubuntu 24.04"
    app: "Denario deep research application"
    hardware: "CPU only"
    packages: "denario, cambagents"
    image_type: "appimage"
    envs:
      IDE_SUFFIX: "tree"
    proxy:
      jupyter:
           token: True
           default: True
           port: 8501
      testurl:
           token: False
           default: False
           port: 9000
