- image:
    registry: "image-registry.vo.elte.hu"
    command: "/entrypoint.sh"
    os: "Ubuntu 24.04"
    app: "Jupyter and Python, Denario scientific research app with AI"
    hardware: "CPU only"
    packages: "conda, uv and basic packages for handling data and plotting results"
    image_type: "projectimage"
  proxy:
    jupyter:
         register: True
         svc_port: 8000
    denario:
         register: True
         basepath: "notebook/report/{container.label}"
         svc_hostname: "{container.label}"
         svc_port: 9000
  service_view:
    denario-app:
      proxy: "denario"
      suffix: "lab"
      openable: True
      pass_token: False
      icon: jupyter
