- image:
    name: "image-registry.vo.elte.hu/report-flask-v8"
    command: "/entrypoint.sh && nice -n 19 /usr/local/bin/runjupyter.sh --config=/etc/jupyter_notebook_config.py --NotebookApp.base_url=$NB_URL --NotebookApp.port=$NB_PORT --NotebookApp.token=$NB_TOKEN"
    os: "Ubuntu 24.04"
    app: "Jupyter and Python"
    hardware: "CPU only"
    packages: "flask"
    image_type: "reportimage"
    proxy:
      jupyter:
           token: True
           default: True
           port: 8000
      testurl:
           token: False
           default: False
           port: 9000
